### PR TITLE
Update SC chair term from 6 to 12 months

### PR DESCRIPTION
**Pull request by alexgleith**
Pretty simple ;-) 

I didn't add anything about the July changeover... that might be able to be weaved into the wording.

### CODE REVIEW

**Comment by gamedaygeorge** [comment]
No need to mention specific month windows I think; could consider 'up to twelve months' type words?

**Comment by alexgleith** [comment]
I guess so. What do you think, @woodcockr?

**Comment by gamedaygeorge** [comment]
We could make it, "... reside in that role for a period of _**up to**_ twelve months in duration..."? Would be good to close it out either way.

**Comment by woodcockr** [comment]
@gamedaygeorge your wording sounds good. I think an upper limit is good but variable duration might suit people's ability to commit.

**Comment by gamedaygeorge** [comment]
@alexgleith @woodcockr just wondering if there's anything else we need to do to close out this PR...? Would be good to have it bedded down with the coming end of Rob's SC Chair term.

**Review by woodcockr — APPROVED** [review]
Tweaked the duration to be a limit per discussions

**Pull request merged**
