### PR TITLE
Update SC membership

### PR DESCRIPTION
**Pull request by SpacemanPaul**
A few corrections that seemed obvious to me.

### CODE REVIEW

**Review by woodcockr — APPROVED** [review]
LGTM

**Review by alexgleith — COMMENTED** [review]
Dave isn't joining, but Damien is.￼

And is Kirill staying on?

**Comment by SpacemanPaul** [comment]
> Dave isn't joining, but Damien is.
Will fix.

> And is Kirill staying on?

He hasn't formally resigned and I know he hopes to be able to keep working in the ODC community.  

@Kirill888 ?

**Comment by Kirill888** [comment]
I have started contract with Element84 today, it'll be around ODC and STAC, so If I can stay on, I would like to do so.

**Comment by alexgleith** [comment]
That's great, Kirill! Nice work on the E84 gig 🙂

**Review by Kirill888 — APPROVED** [review]

**Review by alexgleith — APPROVED** [review]
Approved. I thought I made half these changes the other day! Mustn't have pushed.

Anyhow, thanks Paul 🙂

**Comment by SpacemanPaul** [comment]
> I have started contract with Element84 today, it'll be around ODC and STAC, so If I can stay on, I would like to do so.

That's great news, congratulations.  See you around on Slack then - and at Steering Council meetings!

**Pull request merged**
